#!/usr/bin/env python3
"""
generate_container_header.py - emit a type-specific container header.

One invocation = one header = one container kind for one element type.

Examples:
    # Heap-backed dynamic array of int32_t
    python tools/generate_container_header.py \\
        --kind vec --type-name int32 --value-type int32_t \\
        --output include/handy_generated/int32_vec.h

    # Fixed-capacity ring buffer of struct event
    python tools/generate_container_header.py \\
        --kind ring --type-name event --value-type "struct event" \\
        --output include/handy_generated/event_ring.h

    # u64-keyed hash map of struct user *
    python tools/generate_container_header.py \\
        --kind map_u64 --type-name user --value-type "struct user *" \\
        --output include/handy_generated/user_map.h

    # hs_str-keyed hash map of int
    python tools/generate_container_header.py \\
        --kind map_str --type-name word_count --value-type int \\
        --output include/handy_generated/word_count_map.h

All emitted headers depend on `handy/handy_safety.h` (HS_OK / hs_status).
map_str additionally depends on `handy/handy_str.h`.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def header_guard(path: Path) -> str:
    name = re.sub(r"[^A-Za-z0-9]", "_", path.name).upper()
    return f"HANDY_GEN_{name}"


VEC_TEMPLATE = r"""/* AUTO-GENERATED by tools/generate_container_header.py. Do not edit. */
#ifndef {guard}
#define {guard}

#include <stddef.h>
#include <stdlib.h>
#include <string.h>

#include "handy/handy_safety.h"

#ifdef __cplusplus
extern "C" {{
#endif

typedef struct {{
    {value} *data;
    size_t len;
    size_t capacity;
    unsigned char owns_heap;
}} {name}_vec;

static inline void {name}_vec_init({name}_vec *v) {{
    v->data = NULL; v->len = 0; v->capacity = 0; v->owns_heap = 1;
}}

static inline void {name}_vec_init_from_buffer({name}_vec *v,
                                                {value} *buffer, size_t capacity) {{
    v->data = buffer; v->len = 0; v->capacity = capacity; v->owns_heap = 0;
}}

static inline void {name}_vec_free({name}_vec *v) {{
    if (v->owns_heap && v->data != NULL) {{ free(v->data); }}
    v->data = NULL; v->len = 0; v->capacity = 0;
}}

static inline HS_NODISCARD hs_status {name}_vec_reserve({name}_vec *v, size_t needed) {{
    if (needed <= v->capacity) {{ return HS_OK; }}
    if (!v->owns_heap) {{ return HS_ERR_CAP; }}
    size_t new_cap = v->capacity == 0 ? 8 : v->capacity;
    while (new_cap < needed) {{ new_cap *= 2; }}
    {value} *p = ({value} *)realloc(v->data, new_cap * sizeof(*p));
    if (p == NULL) {{ return HS_ERR_CAP; }}
    v->data = p; v->capacity = new_cap;
    return HS_OK;
}}

static inline HS_NODISCARD hs_status {name}_vec_push({name}_vec *v, {value} value) {{
    hs_status s = {name}_vec_reserve(v, v->len + 1);
    if (s != HS_OK) {{ return s; }}
    v->data[v->len++] = value;
    return HS_OK;
}}

static inline unsigned char {name}_vec_pop({name}_vec *v, {value} *out) {{
    if (v->len == 0) {{ return 0; }}
    v->len--;
    if (out != NULL) {{ *out = v->data[v->len]; }}
    return 1;
}}

static inline HS_NODISCARD hs_status {name}_vec_get(const {name}_vec *v,
                                                    size_t index, {value} *out) {{
    if (index >= v->len) {{ return HS_ERR_BOUNDS; }}
    *out = v->data[index];
    return HS_OK;
}}

static inline HS_NODISCARD hs_status {name}_vec_set({name}_vec *v,
                                                    size_t index, {value} value) {{
    if (index >= v->len) {{ return HS_ERR_BOUNDS; }}
    v->data[index] = value;
    return HS_OK;
}}

static inline size_t {name}_vec_len(const {name}_vec *v) {{ return v->len; }}
static inline {value} *{name}_vec_data({name}_vec *v) {{ return v->data; }}
static inline void {name}_vec_clear({name}_vec *v) {{ v->len = 0; }}

#define {NAME}_VEC_FOR_EACH(it, v) \
    for (size_t _hs_i = 0; _hs_i < (v)->len && (((it) = (v)->data[_hs_i]), 1); ++_hs_i)

#ifdef __cplusplus
}}
#endif
#endif
"""

RING_TEMPLATE = r"""/* AUTO-GENERATED by tools/generate_container_header.py. Do not edit. */
#ifndef {guard}
#define {guard}

#include <stddef.h>

#include "handy/handy_safety.h"

#ifdef __cplusplus
extern "C" {{
#endif

typedef struct {{
    {value} *data;
    size_t capacity;
    size_t head;
    size_t tail;
    size_t count;
}} {name}_ring;

static inline void {name}_ring_init({name}_ring *r, {value} *buffer, size_t capacity) {{
    r->data = buffer; r->capacity = capacity;
    r->head = 0; r->tail = 0; r->count = 0;
}}

static inline size_t {name}_ring_len(const {name}_ring *r) {{ return r->count; }}
static inline unsigned char {name}_ring_is_empty(const {name}_ring *r) {{ return (unsigned char)(r->count == 0); }}
static inline unsigned char {name}_ring_is_full(const {name}_ring *r) {{ return (unsigned char)(r->count == r->capacity); }}

static inline HS_NODISCARD hs_status {name}_ring_push({name}_ring *r, {value} value) {{
    if (r->count == r->capacity) {{ return HS_ERR_CAP; }}
    r->data[r->tail] = value;
    r->tail = (r->tail + 1) % r->capacity;
    r->count++;
    return HS_OK;
}}

static inline HS_NODISCARD hs_status {name}_ring_pop({name}_ring *r, {value} *out) {{
    if (r->count == 0) {{ return HS_ERR_BOUNDS; }}
    *out = r->data[r->head];
    r->head = (r->head + 1) % r->capacity;
    r->count--;
    return HS_OK;
}}

static inline HS_NODISCARD hs_status {name}_ring_peek(const {name}_ring *r, {value} *out) {{
    if (r->count == 0) {{ return HS_ERR_BOUNDS; }}
    *out = r->data[r->head];
    return HS_OK;
}}

static inline void {name}_ring_clear({name}_ring *r) {{
    r->head = 0; r->tail = 0; r->count = 0;
}}

#ifdef __cplusplus
}}
#endif
#endif
"""

MAP_U64_TEMPLATE = r"""/* AUTO-GENERATED by tools/generate_container_header.py. Do not edit. */
#ifndef {guard}
#define {guard}

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "handy/handy_safety.h"

#ifdef __cplusplus
extern "C" {{
#endif

/* Open-addressing hash map with linear probing and tombstones.
 * Capacity is always a power of two; grows when load (count+tombstones) > 7/8. */

#define {NAME}_MAP_STATE_EMPTY     0u
#define {NAME}_MAP_STATE_USED      1u
#define {NAME}_MAP_STATE_TOMBSTONE 2u

typedef struct {{
    uint64_t key;
    {value} value;
    unsigned char state;
}} {name}_map_entry;

typedef struct {{
    {name}_map_entry *entries;
    size_t capacity;       /* power of two */
    size_t count;
    size_t tombstones;
}} {name}_map_u64;

static inline uint64_t {name}_map_hash_(uint64_t x) {{
    x ^= x >> 30; x *= 0xbf58476d1ce4e5b9ull;
    x ^= x >> 27; x *= 0x94d049bb133111ebull;
    x ^= x >> 31; return x;
}}

static inline HS_NODISCARD hs_status {name}_map_u64_init({name}_map_u64 *m, size_t initial_capacity) {{
    size_t cap = 16;
    while (cap < initial_capacity) {{ cap *= 2; }}
    m->entries = ({name}_map_entry *)calloc(cap, sizeof(*m->entries));
    if (m->entries == NULL) {{ return HS_ERR_CAP; }}
    m->capacity = cap; m->count = 0; m->tombstones = 0;
    return HS_OK;
}}

static inline void {name}_map_u64_free({name}_map_u64 *m) {{
    if (m->entries != NULL) {{ free(m->entries); }}
    m->entries = NULL; m->capacity = 0; m->count = 0; m->tombstones = 0;
}}

static inline size_t {name}_map_u64_len(const {name}_map_u64 *m) {{ return m->count; }}

/* Find slot for key. Returns index. If found, slot is USED with matching key.
 * If not found, slot is the first EMPTY slot in the probe chain (insert here),
 * unless include_tombstones=1 in which case the first TOMBSTONE is preferred
 * (for inserts). */
static inline size_t {name}_map_find_slot_(const {name}_map_u64 *m, uint64_t key,
                                            unsigned char for_insert) {{
    size_t mask = m->capacity - 1;
    size_t idx = (size_t){name}_map_hash_(key) & mask;
    size_t first_tomb = (size_t)-1;
    for (;;) {{
        unsigned char st = m->entries[idx].state;
        if (st == {NAME}_MAP_STATE_EMPTY) {{
            if (for_insert && first_tomb != (size_t)-1) {{ return first_tomb; }}
            return idx;
        }}
        if (st == {NAME}_MAP_STATE_USED && m->entries[idx].key == key) {{
            return idx;
        }}
        if (st == {NAME}_MAP_STATE_TOMBSTONE && first_tomb == (size_t)-1) {{
            first_tomb = idx;
        }}
        idx = (idx + 1) & mask;
    }}
}}

static inline HS_NODISCARD hs_status {name}_map_u64_resize_({name}_map_u64 *m, size_t new_cap) {{
    {name}_map_entry *old = m->entries;
    size_t old_cap = m->capacity;
    {name}_map_entry *fresh = ({name}_map_entry *)calloc(new_cap, sizeof(*fresh));
    if (fresh == NULL) {{ return HS_ERR_CAP; }}
    m->entries = fresh; m->capacity = new_cap; m->count = 0; m->tombstones = 0;
    for (size_t i = 0; i < old_cap; ++i) {{
        if (old[i].state == {NAME}_MAP_STATE_USED) {{
            size_t slot = {name}_map_find_slot_(m, old[i].key, 1);
            m->entries[slot].key = old[i].key;
            m->entries[slot].value = old[i].value;
            m->entries[slot].state = {NAME}_MAP_STATE_USED;
            m->count++;
        }}
    }}
    free(old);
    return HS_OK;
}}

static inline HS_NODISCARD hs_status {name}_map_u64_put({name}_map_u64 *m,
                                                        uint64_t key, {value} value) {{
    if ((m->count + m->tombstones + 1) * 8 > m->capacity * 7) {{
        hs_status s = {name}_map_u64_resize_(m, m->capacity * 2);
        if (s != HS_OK) {{ return s; }}
    }}
    size_t slot = {name}_map_find_slot_(m, key, 1);
    unsigned char st = m->entries[slot].state;
    if (st != {NAME}_MAP_STATE_USED) {{
        if (st == {NAME}_MAP_STATE_TOMBSTONE) {{ m->tombstones--; }}
        m->count++;
    }}
    m->entries[slot].key = key;
    m->entries[slot].value = value;
    m->entries[slot].state = {NAME}_MAP_STATE_USED;
    return HS_OK;
}}

static inline HS_NODISCARD hs_status {name}_map_u64_get(const {name}_map_u64 *m,
                                                        uint64_t key, {value} *out) {{
    if (m->capacity == 0) {{ return HS_ERR_BOUNDS; }}
    size_t slot = {name}_map_find_slot_(m, key, 0);
    if (m->entries[slot].state != {NAME}_MAP_STATE_USED) {{ return HS_ERR_BOUNDS; }}
    *out = m->entries[slot].value;
    return HS_OK;
}}

static inline unsigned char {name}_map_u64_remove({name}_map_u64 *m, uint64_t key) {{
    if (m->capacity == 0) {{ return 0; }}
    size_t slot = {name}_map_find_slot_(m, key, 0);
    if (m->entries[slot].state != {NAME}_MAP_STATE_USED) {{ return 0; }}
    m->entries[slot].state = {NAME}_MAP_STATE_TOMBSTONE;
    m->count--; m->tombstones++;
    return 1;
}}

#ifdef __cplusplus
}}
#endif
#endif
"""

MAP_STR_TEMPLATE = r"""/* AUTO-GENERATED by tools/generate_container_header.py. Do not edit. */
#ifndef {guard}
#define {guard}

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "handy/handy_safety.h"
#include "handy/handy_str.h"

#ifdef __cplusplus
extern "C" {{
#endif

#define {NAME}_MAP_STATE_EMPTY     0u
#define {NAME}_MAP_STATE_USED      1u
#define {NAME}_MAP_STATE_TOMBSTONE 2u

typedef struct {{
    hs_str key;       /* non-owning; caller keeps key memory alive */
    {value} value;
    unsigned char state;
}} {name}_map_entry;

typedef struct {{
    {name}_map_entry *entries;
    size_t capacity;
    size_t count;
    size_t tombstones;
}} {name}_map_str;

static inline uint64_t {name}_map_hash_str_(hs_str s) {{
    /* FNV-1a 64-bit */
    uint64_t h = 0xcbf29ce484222325ull;
    for (size_t i = 0; i < s.len; ++i) {{
        h ^= (uint64_t)(unsigned char)s.data[i];
        h *= 0x100000001b3ull;
    }}
    return h;
}}

static inline HS_NODISCARD hs_status {name}_map_str_init({name}_map_str *m, size_t initial_capacity) {{
    size_t cap = 16;
    while (cap < initial_capacity) {{ cap *= 2; }}
    m->entries = ({name}_map_entry *)calloc(cap, sizeof(*m->entries));
    if (m->entries == NULL) {{ return HS_ERR_CAP; }}
    m->capacity = cap; m->count = 0; m->tombstones = 0;
    return HS_OK;
}}

static inline void {name}_map_str_free({name}_map_str *m) {{
    if (m->entries != NULL) {{ free(m->entries); }}
    m->entries = NULL; m->capacity = 0; m->count = 0; m->tombstones = 0;
}}

static inline size_t {name}_map_str_len(const {name}_map_str *m) {{ return m->count; }}

static inline size_t {name}_map_find_slot_(const {name}_map_str *m, hs_str key,
                                            unsigned char for_insert) {{
    size_t mask = m->capacity - 1;
    size_t idx = (size_t){name}_map_hash_str_(key) & mask;
    size_t first_tomb = (size_t)-1;
    for (;;) {{
        unsigned char st = m->entries[idx].state;
        if (st == {NAME}_MAP_STATE_EMPTY) {{
            if (for_insert && first_tomb != (size_t)-1) {{ return first_tomb; }}
            return idx;
        }}
        if (st == {NAME}_MAP_STATE_USED && hs_str_eq(m->entries[idx].key, key)) {{
            return idx;
        }}
        if (st == {NAME}_MAP_STATE_TOMBSTONE && first_tomb == (size_t)-1) {{
            first_tomb = idx;
        }}
        idx = (idx + 1) & mask;
    }}
}}

static inline HS_NODISCARD hs_status {name}_map_str_resize_({name}_map_str *m, size_t new_cap) {{
    {name}_map_entry *old = m->entries;
    size_t old_cap = m->capacity;
    {name}_map_entry *fresh = ({name}_map_entry *)calloc(new_cap, sizeof(*fresh));
    if (fresh == NULL) {{ return HS_ERR_CAP; }}
    m->entries = fresh; m->capacity = new_cap; m->count = 0; m->tombstones = 0;
    for (size_t i = 0; i < old_cap; ++i) {{
        if (old[i].state == {NAME}_MAP_STATE_USED) {{
            size_t slot = {name}_map_find_slot_(m, old[i].key, 1);
            m->entries[slot].key = old[i].key;
            m->entries[slot].value = old[i].value;
            m->entries[slot].state = {NAME}_MAP_STATE_USED;
            m->count++;
        }}
    }}
    free(old);
    return HS_OK;
}}

static inline HS_NODISCARD hs_status {name}_map_str_put({name}_map_str *m,
                                                        hs_str key, {value} value) {{
    if ((m->count + m->tombstones + 1) * 8 > m->capacity * 7) {{
        hs_status s = {name}_map_str_resize_(m, m->capacity * 2);
        if (s != HS_OK) {{ return s; }}
    }}
    size_t slot = {name}_map_find_slot_(m, key, 1);
    unsigned char st = m->entries[slot].state;
    if (st != {NAME}_MAP_STATE_USED) {{
        if (st == {NAME}_MAP_STATE_TOMBSTONE) {{ m->tombstones--; }}
        m->count++;
    }}
    m->entries[slot].key = key;
    m->entries[slot].value = value;
    m->entries[slot].state = {NAME}_MAP_STATE_USED;
    return HS_OK;
}}

static inline HS_NODISCARD hs_status {name}_map_str_get(const {name}_map_str *m,
                                                        hs_str key, {value} *out) {{
    if (m->capacity == 0) {{ return HS_ERR_BOUNDS; }}
    size_t slot = {name}_map_find_slot_(m, key, 0);
    if (m->entries[slot].state != {NAME}_MAP_STATE_USED) {{ return HS_ERR_BOUNDS; }}
    *out = m->entries[slot].value;
    return HS_OK;
}}

static inline unsigned char {name}_map_str_remove({name}_map_str *m, hs_str key) {{
    if (m->capacity == 0) {{ return 0; }}
    size_t slot = {name}_map_find_slot_(m, key, 0);
    if (m->entries[slot].state != {NAME}_MAP_STATE_USED) {{ return 0; }}
    m->entries[slot].state = {NAME}_MAP_STATE_TOMBSTONE;
    m->count--; m->tombstones++;
    return 1;
}}

#ifdef __cplusplus
}}
#endif
#endif
"""


KINDS = {
    "vec":     VEC_TEMPLATE,
    "ring":    RING_TEMPLATE,
    "map_u64": MAP_U64_TEMPLATE,
    "map_str": MAP_STR_TEMPLATE,
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--kind", required=True, choices=sorted(KINDS.keys()))
    ap.add_argument("--type-name", required=True,
                    help="Identifier prefix for generated types/functions, e.g. 'event'")
    ap.add_argument("--value-type", required=True,
                    help='C value type, e.g. "int32_t" or "struct event *"')
    ap.add_argument("--output", required=True, type=Path,
                    help="Output header path")
    args = ap.parse_args()

    if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", args.type_name):
        print(f"error: --type-name must be a C identifier: {args.type_name!r}",
              file=sys.stderr)
        return 2

    args.output.parent.mkdir(parents=True, exist_ok=True)
    template = KINDS[args.kind]
    rendered = template.format(
        guard=header_guard(args.output),
        name=args.type_name,
        NAME=args.type_name.upper(),
        value=args.value_type,
    )
    args.output.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.output}  ({args.kind} of {args.value_type})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
